coverage:
  status:
    project:
      default:
        branches:
          - dev
          - 'release-*'
        if_not_found: failure
        target: auto
        threshold: 0.1%
    patch:
      default:
        if_not_found: success
        target: auto
        threshold: 0.1%
ignore:
  - "binrz/rz-test"
  - ".github"
  - "doc"
  - "man"
  - "mk"
  - "sys"
  - "test"

comment:
  layout: "header, files, components, footer"
  require_changes: true
